/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlueprintBox: typeof import('./src/components/BlueprintBox.vue')['default']
    Decode: typeof import('./src/components/Decode.vue')['default']
    DirectionRadio: typeof import('./src/components/DirectionRadio.vue')['default']
    ItemSelect: typeof import('./src/components/ItemSelect.vue')['default']
    Lamps: typeof import('./src/components/Lamps.vue')['default']
    Printer: typeof import('./src/components/Printer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SizeSelect: typeof import('./src/components/SizeSelect.vue')['default']
    SnackBar: typeof import('./src/components/SnackBar.vue')['default']
  }
}
